### ISSUE TITLE
Crash in LAN-Multiplayer as client

### ISSUE THREAD

**Issue by titison** [MegaGlest/megaglest-source#80] opened 2015-10-25 13:31 UTC
Crash during a multiplayer game when i was connected to a non-headless server.
http://pastebin.com/0rKTsDkq
I am not sure if this is related to the sdl2 feature but it occurred within the sdl2 branch.
EDIT: ignore the first error messages about the tileset. I don't have a tileset which the server choose first.
EDIT2: Maybe I should add that this always happened when I used a group key to select the a group.

**Comment by filux** [comment] 2015-10-25 13:50
and as classic code ;) :
``` c++
megaglest v3.12-dev
Compiled using: GNUC: 40804 [64bit] on: Oct 25 2015 13:37:16 platform: Linux-X64 endianness: little
GIT: [Rev: 5199.7190293] - using STREFLOP [SSE] - [no-denormals]
Game unique identifier is: f0b81420-7b15-11e5-807d-d717768bef90
*ERROR* [2015-10-25 13:46:46] In [network_interface.cpp::DisplayErrorMessage Line: 198] sErr [Player titi_son, disconnected from the game.]
curl FAILED with: 78 [Remote file not found] attempting to remove folder contents [/home/tscharn/.megaglest/tilesets/] szBuf [ftp://tilesets_custom:mg_ftp_server@192.168.178.52:61368/pandora_a2.7z] ftpfile.isValidXfer = 0, pathCreated = 0
curl FAILED with: 78 [Remote file not found] attempting to remove folder contents [/home/tscharn/.megaglest/tilesets/] szBuf [ftp://tilesets_custom:mg_ftp_server@192.168.178.52:61368/pandora_a2.7z] ftpfile.isValidXfer = 0, pathCreated = 0
curl FAILED with: 78 [Remote file not found] attempting to remove folder contents [/home/tscharn/.megaglest/tilesets/] szBuf [ftp://tilesets:mg_ftp_server@192.168.178.52:61368/pandora_a2.7z] ftpfile.isValidXfer = 0, pathCreated = 0
Game unique identifier is: 8c00a5aa-7b16-11e5-923b-092a5004190e
In [/home/tscharn/gitglest/source/glest_game/main/main.cpp::handleSIGSEGV Line: 5706] Error detected: signal 11:
Error saved to logfile [/home/tscharn/.megaglest/error.log]
*ERROR* [2015-10-25 14:01:13] In [/home/tscharn/gitglest/source/glest_game/main/main.cpp::handleRuntimeError Line: 640] [In [/home/tscharn/gitglest/source/glest_game/main/main.cpp::handleSIGSEGV Line: 5706] Error detected: signal 11:
] gameInitialized = 1, program = 0x181a880
*ERROR* [2015-10-25 14:01:14] In [/home/tscharn/gitglest/source/glest_game/main/main.cpp::handleRuntimeError Line: 659] [In [/home/tscharn/gitglest/source/glest_game/main/main.cpp::handleSIGSEGV Line: 5706] Error detected: signal 11:
 
Stack Trace:
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::ExceptionHandler::handleRuntimeError(char const*, bool)address [0x6d4c42] line: 650
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::handleSIGSEGV(int)address [0x6d4f58] line: 5711
/lib/x86_64-linux-gnu/libc.so.6:()address [0x7f264ff78d40] line: 0
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Gui::computeDisplay()address [0x69b1f2] line: 857
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Selection::select(Glest::Game::Unit*)address [0x6943ec] line: 122
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Selection::recallGroup(int, bool)address [0x694903] line: 274
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Gui::groupKey(int)address [0x6a0835] line: 370
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Game::keyDown(SDL_KeyboardEvent)address [0x5cc876] line: 4879
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Program::keyDown(SDL_KeyboardEvent)address [0x6abfe8] line: 351
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::MainWindow::eventKeyDown(SDL_KeyboardEvent)address [0x6b8d86] line: 1128
/home/tscharn/gitglest/mk/linux/megaglest:Shared::Platform::Window::handleEvent()address [0xb10a6d] line: 327
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::glestMain(int, char**)address [0x6e1ec7] line: 5468
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::glestMainSEHWrapper(int, char**)address [0x6e8326] line: 5803
/lib/x86_64-linux-gnu/libc.so.6:__libc_start_main()address [0x7f264ff63ec5] line: 0
/home/tscharn/gitglest/mk/linux/megaglest() [0x4ee0ba]address [0x4ee0ba]
]
 
=====================================
 
** Already in error handler exiting errror rendering, msg [arrayIndex >= getCellArraySize(), arrayIndex = 445369416 w = 1065353216 h = 1065353216
Stack Trace:
/home/tscharn/gitglest/mk/linux/megaglest:Shared::Platform::megaglest_runtime_error::megaglest_runtime_error(std::string const&, bool)address [0xb198fd] line: 338
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Unit::computeHeight(Shared::Graphics::Vec2<int> const&) constaddress [0x91e44f] line: 3712
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Unit::getVectorFlat(Shared::Graphics::Vec2<int> const&, Shared::Graphics::Vec2<int> const&) constaddress [0x91ecd6] line: 1673
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Unit::getCurrVectorFlat() constaddress [0x91eec7] line: 1661
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Renderer::renderSelectionEffects(int)address [0x65e625] line: 5540
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Game::render3d()address [0x5bc429] line: 5266
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Game::renderWorker()address [0x5c0c28] line: 3299
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Game::render()address [0x5c1138] line: 3258
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Program::loopWorker()address [0x6a9130] line: 446
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::ExceptionHandler::handleRuntimeError(char const*, bool)address [0x6d4afb] line: 679
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::handleSIGSEGV(int)address [0x6d4f58] line: 5711
/lib/x86_64-linux-gnu/libc.so.6:()address [0x7f264ff78d40] line: 0
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Gui::computeDisplay()address [0x69b1f2] line: 857
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Selection::select(Glest::Game::Unit*)address [0x6943ec] line: 122
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Selection::recallGroup(int, bool)address [0x694903] line: 274
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Gui::groupKey(int)address [0x6a0835] line: 370
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Game::keyDown(SDL_KeyboardEvent)address [0x5cc876] line: 4879
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::Program::keyDown(SDL_KeyboardEvent)address [0x6abfe8] line: 351
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::MainWindow::eventKeyDown(SDL_KeyboardEvent)address [0x6b8d86] line: 1128
/home/tscharn/gitglest/mk/linux/megaglest:Shared::Platform::Window::handleEvent()address [0xb10a6d] line: 327
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::glestMain(int, char**)address [0x6e1ec7] line: 5468
/home/tscharn/gitglest/mk/linux/megaglest:Glest::Game::glestMainSEHWrapper(int, char**)address [0x6e8326] line: 5803
/lib/x86_64-linux-gnu/libc.so.6:__libc_start_main()address [0x7f264ff63ec5] line: 0
/home/tscharn/gitglest/mk/linux/megaglest() [0x4ee0ba]address [0x4ee0ba]
]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x28f52a0] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x28f52a0] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x28f52a0] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x28f52a0] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x28f52a0] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x28f52a0] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x28f52a0] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x28f52a0] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x28f52a0] isBaseThread: 1, Name: [SimpleTaskThread]
Aborted (core dumped)
```

**Comment by titison** [comment] 2015-10-25 14:16
well titi told me to use pastebin ^^
we had the same issue now one the servers side and again on the clients side. First the client and some minutes later the server.

**Comment by filux** [comment] 2015-10-25 14:24
> ( and i always forget how to use code on github :D )

heh it's harder to write here how to use it than use it :)
 ```
~~~ (< without shift)
code
~~~ (< without shift)
```

**Comment by titiger** [comment] 2015-10-25 14:30
and here one more form another game where both of us crashed ( 30 minutes in game ) here my stacktrace:

```tscharn@p2x4:~/gitglest/mk/linux$ ./megaglest
megaglest v3.12-dev
Compiled using: GNUC: 40804 [64bit] on: Oct 25 2015 13:37:15 platform: Linux-X64 endianness: little
GIT: [Rev: 5199.7190293] - using STREFLOP [SSE] - [no-denormals]
Game unique identifier is: 8b148dfe-7b1c-11e5-b2c2-2f5036c4702f
Game unique identifier is: 09ebaf7c-7b1d-11e5-9f35-2f5036c4702f
In [/home/tscharn/gitglest/source/glest_game/main/main.cpp::handleSIGSEGV Line: 5706] Error detected: signal 11:
Error saved to logfile [/home/tscharn/.megaglest/error.log]
*ERROR* [2015-10-25 15:12:14] In [/home/tscharn/gitglest/source/glest_game/main/main.cpp::handleRuntimeError Line: 640] [In [/home/tscharn/gitglest/source/glest_game/main/main.cpp::handleSIGSEGV Line: 5706] Error detected: signal 11:
] gameInitialized = 1, program = 0x2e1e880
*ERROR* [2015-10-25 15:12:16] In [/home/tscharn/gitglest/source/glest_game/main/main.cpp::handleRuntimeError Line: 659] [In [/home/tscharn/gitglest/source/glest_game/main/main.cpp::handleSIGSEGV Line: 5706] Error detected: signal 11:

Stack Trace:
./megaglest:Glest::Game::ExceptionHandler::handleRuntimeError(char const*, bool)address [0x6d10d2] line: 650
./megaglest:Glest::Game::handleSIGSEGV(int)address [0x6d13e8] line: 5711
/lib/x86_64-linux-gnu/libc.so.6:()address [0x7f3b5f5abd40] line: 0
./megaglest:Glest::Game::Gui::computeDisplay()address [0x6981e2] line: 857
./megaglest:Glest::Game::Selection::select(Glest::Game::Unit*)address [0x6a0b6c] line: 122
./megaglest:Glest::Game::Selection::recallGroup(int, bool)address [0x6a1083] line: 274
./megaglest:Glest::Game::Gui::groupKey(int)address [0x69d825] line: 370
./megaglest:Glest::Game::Game::keyDown(SDL_KeyboardEvent)address [0x5b8036] line: 4879
./megaglest:Glest::Game::Program::keyDown(SDL_KeyboardEvent)address [0x6f5788] line: 351
./megaglest:Glest::Game::MainWindow::eventKeyDown(SDL_KeyboardEvent)address [0x6b5216] line: 1128
./megaglest:Shared::Platform::Window::handleEvent()address [0xb1886d] line: 327
./megaglest:Glest::Game::glestMain(int, char**)address [0x6de357] line: 5468
./megaglest:Glest::Game::glestMainSEHWrapper(int, char**)address [0x6e47b6] line: 5803
/lib/x86_64-linux-gnu/libc.so.6:__libc_start_main()address [0x7f3b5f596ec5] line: 0
./megaglest() [0x4ee0ba]address [0x4ee0ba]
]

=====================================

** Already in error handler exiting errror rendering, msg [arrayIndex >= getCellArraySize(), arrayIndex = 488266520 w = 1065353216 h = 1065353216
Stack Trace:
./megaglest:Shared::Platform::megaglest_runtime_error::megaglest_runtime_error(std::string const&, bool)address [0xb216fd] line: 338
./megaglest:Glest::Game::Unit::computeHeight(Shared::Graphics::Vec2<int> const&) constaddress [0x92245f] line: 3712
./megaglest:Glest::Game::Unit::getVectorFlat(Shared::Graphics::Vec2<int> const&, Shared::Graphics::Vec2<int> const&) constaddress [0x922ce6] line: 1673
./megaglest:Glest::Game::Unit::getCurrVectorFlat() constaddress [0x922ed7] line: 1661
./megaglest:Glest::Game::Renderer::renderSelectionEffects(int)address [0x652b75] line: 5540
./megaglest:Glest::Game::Game::render3d()address [0x5a7be9] line: 5266
./megaglest:Glest::Game::Game::renderWorker()address [0x5ac3e8] line: 3299
./megaglest:Glest::Game::Game::render()address [0x5ac8f8] line: 3258
./megaglest:Glest::Game::Program::loopWorker()address [0x6f28d0] line: 446
./megaglest:Glest::Game::ExceptionHandler::handleRuntimeError(char const*, bool)address [0x6d0f8b] line: 679
./megaglest:Glest::Game::handleSIGSEGV(int)address [0x6d13e8] line: 5711
/lib/x86_64-linux-gnu/libc.so.6:()address [0x7f3b5f5abd40] line: 0
./megaglest:Glest::Game::Gui::computeDisplay()address [0x6981e2] line: 857
./megaglest:Glest::Game::Selection::select(Glest::Game::Unit*)address [0x6a0b6c] line: 122
./megaglest:Glest::Game::Selection::recallGroup(int, bool)address [0x6a1083] line: 274
./megaglest:Glest::Game::Gui::groupKey(int)address [0x69d825] line: 370
./megaglest:Glest::Game::Game::keyDown(SDL_KeyboardEvent)address [0x5b8036] line: 4879
./megaglest:Glest::Game::Program::keyDown(SDL_KeyboardEvent)address [0x6f5788] line: 351
./megaglest:Glest::Game::MainWindow::eventKeyDown(SDL_KeyboardEvent)address [0x6b5216] line: 1128
./megaglest:Shared::Platform::Window::handleEvent()address [0xb1886d] line: 327
./megaglest:Glest::Game::glestMain(int, char**)address [0x6de357] line: 5468
./megaglest:Glest::Game::glestMainSEHWrapper(int, char**)address [0x6e47b6] line: 5803
/lib/x86_64-linux-gnu/libc.so.6:__libc_start_main()address [0x7f3b5f596ec5] line: 0
./megaglest() [0x4ee0ba]address [0x4ee0ba]
]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x3ee2c00] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x3ee2c00] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x3ee2c00] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x3ee2c00] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x3ee2c00] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x3ee2c00] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x3ee2c00] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x3ee2c00] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x3ee2c00] isBaseThread: 1, Name: [SimpleTaskThread]
Waiting for the following threads to exit [1]:
Thread index: 0 ptr [0x3ee2c00] isBaseThread: 1, Name: [SimpleTaskThread]
Abgebrochen (Speicherabzug geschrieben)
tscharn@p2x4:~/gitglest/mk/linux$ 
```

**Comment by softcoder** [comment] 2015-10-26 20:06
Can nayone reproduce using latest git code and offer a stacktrace?

**Comment by titiger** [comment] 2015-11-01 21:46
Not reproduced yet, it must be something special my son does while playing, it was always him who crashed it . I try to motivate him to test play again ;-)

**Comment by titiger** [comment] 2015-11-01 23:56
ok I found the bug ( my bug ) now and I will fix it tomorrow. Its related to add units to a group. 

Currently problem is you can:
1. add more units to a group then the allowed selection size, So a group size can be bigger than the allowed selection size. 
2. you can add the same unit multiple times to the same group ( and I bet cleanup is bad with this )

**Comment by titiger** [comment] 2015-11-15 20:16
Looks like this is fixed now

**Closed by titiger** 2015-11-15 20:16 UTC
