### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kozross** [MegaGlest/megaglest-source#68] opened 2015-08-12 22:47 UTC
While I know you guys are free software, it'd be nice to have a license file explaining what license you guys use.

**Comment by alketii** [comment] 2015-08-12 22:49
Well it doesn't have a License file in source code, but its mentioned in every cpp file and in binary installers.

**Comment by tomreyn** [comment] 2015-08-13 13:07
Did you actually spend time on looking for this information?

https://github.com/MegaGlest/megaglest-source/tree/master/docs

**Comment by tomreyn** [comment] 2015-08-14 21:27
Sorry about the bad tone I picked, I was just disappointed that Koz was unable to spot the copyright declaration and license text in the "docs" subdirectory on his own.

Anyways, it's there, so this is not a bug - closing. (Please feel free to contact us by e-mail should you think differently or in case I misunderstood the bug report).

**Closed** 2015-08-28 18:35 UTC
