### ISSUE TITLE
Making the build reproducible

### ISSUE THREAD

**Issue by apoleon** [MegaGlest/megaglest-source#83] opened 2015-11-14 11:41 UTC
Hi,

Debian tries to achieve that every binary package can be built reproducibly from a given source. 

https://wiki.debian.org/ReproducibleBuilds
https://wiki.debian.org/ReproducibleBuilds/About

This has various advantages for users which are outlined on the pages I have linked to. Currently Megaglest cannot be built reproducibly because it uses __DATE__ and __TIME__ macros to capture the current date and time. I have removed those macros with the following patch.

https://sources.debian.net/src/megaglest/3.11.1-3/debian/patches/reproducible-build.patch/

I wouldn't mind the Git revision. I think people are more interested in versions than in knowing when a certain package was built. It would be nice if those macros could be removed or replaced.

**Comment by tomreyn** [comment] 2015-11-14 18:29
I'm interested in MG supporting reproducible builds. 

(Debian developer) Pabs suggested that we could use the last source change date instead of the build date. He suggests to use the SOURCE_DATE_EPOCH environment variable if it is set: https://reproducible-builds.org/specs/source-date-epoch/

General information: 
https://reproducible-builds.org/

Debian specific info: 
https://wiki.debian.org/ReproducibleBuilds

Softcoder said this:
* I guess the date removal is ok
* Should we apply the Debian date time changes? We need to check with Titi.

**Comment by filux** [comment] 2015-11-15 08:24
Imo SOURCE_DATE_EPOCH is basically useless for upstream and for downstream too.
This is maybe useful for some users/players (with soul of troll) to know: "how dead is project".

*When time stamp is/was useful?*
For developers and mostly during development tests **or** during resolving some bugs reported by users of "our standalone" packages.

*When MG may have problems without time stamp?*
e.g. During producing standalone packages, especially not first time with same source (build2, build3, ...) & then resolving bugs reported from users when most of them of course won't know which build they are using (because of not keeping archive/installer which is normal).

**Comment by titiger** [comment] 2015-11-16 00:02
If I remember right, the timestamps were added to avoid compatibility trouble with builds from compilers which produce incompatible float results.
On development it helped a bit to see if people did a fresh build or not when testing dev version.

**Comment by wrapperband** [comment] 2015-11-16 10:12
Perhaps you could make it the date of the last commit (or such), it would be reproducible, but you could see if a build had been made?

**Comment by softcoder** [comment] 2015-11-19 01:23
No need for dates just look at GIT and you have the date of the code change. We really should not care when it was built.

**Comment by softcoder** [comment] 2015-11-23 05:31
This was integrated into develop

**Closed by softcoder** 2015-11-23 05:31 UTC
Labels: enhancement
