### ISSUE TITLE
windows client has huge command delay on start

### ISSUE THREAD

**Issue by titiger** [MegaGlest/megaglest-source#92] opened 2015-12-14 22:22 UTC
When a network game starts ( using the headless server ) windows clients have a huge command delay when the game started. This means if you give a command to a worker, it takes several seconds until the unit starts to move. The next thing you see is that the game is catching up with tiny speedups.
After round about 1 minute the game has catched up and the units react immidiatly.
Both tomreyn and me could reproduce this on nearly every start. adn we have very different hardware configs.

Another thing I had was a hard freeze of the windows client ( I had this freeze 2 times today ). ctrl-alt-del brought up the taskmanager and I was able to kill the process. On the CMD-Console I saw message about beeing disconnected from the server, but I am not too sure this was the reason or just a reaction to the freeze.

**Comment by softcoder** [comment] 2015-12-16 02:29
Can you confirm you do not have values for these settings in any ini files?
SimulateClientLag=x
SimulateClientLagDurationSeconds=x

**Comment by titiger** [comment] 2015-12-16 19:00
I confirm, I have no such settings.

**Comment by tomreyn** [comment] 2015-12-16 21:16
I have not actually verified it, but since my test system is a new Windows (10) installation (with the network delay registry patch applied) I highly doubt that these non default options are configured.

**Comment by titiger** [comment] 2015-12-16 21:27
I could reproduce it too each time I tried.

**Comment by tomreyn** [comment] 2015-12-19 16:20
During a test with Alket I could still reproduce it. I was using this snapshot:
```
mg-binary-windows-64bit-3.12-dev-develop.7z        17-Dec-2015 22:15            11779493
```

My test scenario was a little bit different this time, since I was installing Visual Studio at the same time, keeping the disk somewhat busy. It does not feel like this issue is just disk bound, though.

**Comment by filux** [comment] 2015-12-19 16:51
> Project megaglest-source_w64
> #93 ​- ​origin/develop
> 2015-12-17 23:09
> 5303.fd83834

**Comment by titiger** [comment] 2015-12-23 22:19
the freezes I mentioned are gone now with a8b735ffcc9816612bc85abaf1ce61bdfa6b85db

**Comment by titiger** [comment] 2015-12-26 01:37
Filux had the command delay on linux too today. He was slow loading like windows clients do typically.
So it looks like this is not something windows specific.

**Comment by tomreyn** [comment] 2016-01-06 06:14
For me this has not occurred for a while now.

**Comment by filux** [comment] 2016-02-04 16:21
issue seems to be ready for closing

**Closed by filux** 2016-02-04 16:21 UTC
Labels: minor bug
